import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import "@mantine/core/styles.css";
import { MantineProvider } from "@mantine/core";
import { Nav } from "@/components/nav/nav";
import StyledComponentsRegistry from "@/lib/registry";
import { Footer } from "@/components/footer/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden w-full h-screen bg-[#DFDFDF]">
        <MantineProvider>
          <StyledComponentsRegistry>
            <Nav />
            {children}
            <Footer />
          </StyledComponentsRegistry>
        </MantineProvider>
      </body>
    </html>
  );
}
